In [1]:
df2=pd.read_csv(r"S:\Data analysis\python files\salaries.csv")

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [3]:
df2=pd.read_csv(r"S:\Data analysis\python files\salaries.csv")

In [4]:
df2

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [8]:
df2.shape

(148654, 13)

In [9]:
df2.tail

<bound method NDFrame.tail of             Id       EmployeeName  \
0            1     NATHANIEL FORD
1            2       GARY JIMENEZ
2            3     ALBERT PARDINI
3            4  CHRISTOPHER CHONG
4            5    PATRICK GARDNER
...        ...                ...
148649  148650      Roy I Tillery
148650  148651       Not provided
148651  148652       Not provided
148652  148653       Not provided
148653  148654          Joe Lopez

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60
...                                                ...        ...
148649                                       Custodian       0.00
148650                                    Not provided        NaN
148651                                    Not provided        NaN
148652                                    Not provided        NaN
148653                      Counselor, Log Cabin Ranch       0.00

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011
1         245131.88  137811.38       NaN  538909.28         538909.28  2011
2         106088.18   16452.60       NaN  335279.91         335279.91  2011
3          56120.71  198306.90       NaN  332343.61         332343.61  2011
4           9737.00  182234.59       NaN  326373.19         326373.19  2011
...             ...        ...       ...        ...               ...   ...
148649         0.00       0.00       0.0       0.00              0.00  2014
148650          NaN        NaN       NaN       0.00              0.00  2014
148651          NaN        NaN       NaN       0.00              0.00  2014
148652          NaN        NaN       NaN       0.00              0.00  2014
148653         0.00    -618.13       0.0    -618.13           -618.13  2014

        Notes         Agency  Status
0         NaN  San Francisco     NaN
1         NaN  San Francisco     NaN
2         NaN  San Francisco     NaN
3         NaN  San Francisco     NaN
4         NaN  San Francisco     NaN
...       ...            ...     ...
148649    NaN  San Francisco     NaN
148650    NaN  San Francisco     NaN
148651    NaN  San Francisco     NaN
148652    NaN  San Francisco     NaN
148653    NaN  San Francisco     NaN

[148654 rows x 13 columns]>

In [10]:
df2.tail

<bound method NDFrame.tail of             Id       EmployeeName  \
0            1     NATHANIEL FORD
1            2       GARY JIMENEZ
2            3     ALBERT PARDINI
3            4  CHRISTOPHER CHONG
4            5    PATRICK GARDNER
...        ...                ...
148649  148650      Roy I Tillery
148650  148651       Not provided
148651  148652       Not provided
148652  148653       Not provided
148653  148654          Joe Lopez

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60
...                                                ...        ...
148649                                       Custodian       0.00
148650                                    Not provided        NaN
148651                                    Not provided        NaN
148652                                    Not provided        NaN
148653                      Counselor, Log Cabin Ranch       0.00

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011
1         245131.88  137811.38       NaN  538909.28         538909.28  2011
2         106088.18   16452.60       NaN  335279.91         335279.91  2011
3          56120.71  198306.90       NaN  332343.61         332343.61  2011
4           9737.00  182234.59       NaN  326373.19         326373.19  2011
...             ...        ...       ...        ...               ...   ...
148649         0.00       0.00       0.0       0.00              0.00  2014
148650          NaN        NaN       NaN       0.00              0.00  2014
148651          NaN        NaN       NaN       0.00              0.00  2014
148652          NaN        NaN       NaN       0.00              0.00  2014
148653         0.00    -618.13       0.0    -618.13           -618.13  2014

        Notes         Agency  Status
0         NaN  San Francisco     NaN
1         NaN  San Francisco     NaN
2         NaN  San Francisco     NaN
3         NaN  San Francisco     NaN
4         NaN  San Francisco     NaN
...       ...            ...     ...
148649    NaN  San Francisco     NaN
148650    NaN  San Francisco     NaN
148651    NaN  San Francisco     NaN
148652    NaN  San Francisco     NaN
148653    NaN  San Francisco     NaN

[148654 rows x 13 columns]>

In [11]:
df2.sample(5)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
84302,84303,Kurt A Kraal,"Operating Engineer, Universal",92293.50,6765.16,967.32,32207.10,100025.98,132233.08,2013,NaN,San Francisco,NaN
116592,116593,Michael J Horta,Firefighter,96715.54,17079.84,14194.29,39522.73,127989.67,167512.40,2014,NaN,San Francisco,NaN
109716,109717,Arcelia L Hurtado,"BdComm Mbr, Grp3,M=$50/Mtg",1150.00,0.00,0.00,11.50,1150.00,1161.50,2013,NaN,San Francisco,NaN
105177,105178,Michelle A Chu,Recreation Leader,12891.43,0.00,263.22,131.55,13154.65,13286.20,2013,NaN,San Francisco,NaN
99787,99788,Jose Carlo G Hojilla,Special Nurse,53137.09,1441.39,8777.38,633.59,63355.86,63989.45,2013,NaN,San Francisco,NaN

In [12]:
df2.info

<bound method DataFrame.info of             Id       EmployeeName  \
0            1     NATHANIEL FORD
1            2       GARY JIMENEZ
2            3     ALBERT PARDINI
3            4  CHRISTOPHER CHONG
4            5    PATRICK GARDNER
...        ...                ...
148649  148650      Roy I Tillery
148650  148651       Not provided
148651  148652       Not provided
148652  148653       Not provided
148653  148654          Joe Lopez

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60
...                                                ...        ...
148649                                       Custodian       0.00
148650                                    Not provided        NaN
148651                                    Not provided        NaN
148652                                    Not provided        NaN
148653                      Counselor, Log Cabin Ranch       0.00

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011
1         245131.88  137811.38       NaN  538909.28         538909.28  2011
2         106088.18   16452.60       NaN  335279.91         335279.91  2011
3          56120.71  198306.90       NaN  332343.61         332343.61  2011
4           9737.00  182234.59       NaN  326373.19         326373.19  2011
...             ...        ...       ...        ...               ...   ...
148649         0.00       0.00       0.0       0.00              0.00  2014
148650          NaN        NaN       NaN       0.00              0.00  2014
148651          NaN        NaN       NaN       0.00              0.00  2014
148652          NaN        NaN       NaN       0.00              0.00  2014
148653         0.00    -618.13       0.0    -618.13           -618.13  2014

        Notes         Agency  Status
0         NaN  San Francisco     NaN
1         NaN  San Francisco     NaN
2         NaN  San Francisco     NaN
3         NaN  San Francisco     NaN
4         NaN  San Francisco     NaN
...       ...            ...     ...
148649    NaN  San Francisco     NaN
148650    NaN  San Francisco     NaN
148651    NaN  San Francisco     NaN
148652    NaN  San Francisco     NaN
148653    NaN  San Francisco     NaN

[148654 rows x 13 columns]>

In [13]:
df2.dtypes

Id                    int64
EmployeeName         object
JobTitle             object
BasePay             float64
OvertimePay         float64
OtherPay            float64
Benefits            float64
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status              float64
dtype: object

In [14]:
df2.describe

<bound method NDFrame.describe of             Id       EmployeeName  \
0            1     NATHANIEL FORD
1            2       GARY JIMENEZ
2            3     ALBERT PARDINI
3            4  CHRISTOPHER CHONG
4            5    PATRICK GARDNER
...        ...                ...
148649  148650      Roy I Tillery
148650  148651       Not provided
148651  148652       Not provided
148652  148653       Not provided
148653  148654          Joe Lopez

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60
...                                                ...        ...
148649                                       Custodian       0.00
148650                                    Not provided        NaN
148651                                    Not provided        NaN
148652                                    Not provided        NaN
148653                      Counselor, Log Cabin Ranch       0.00

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011
1         245131.88  137811.38       NaN  538909.28         538909.28  2011
2         106088.18   16452.60       NaN  335279.91         335279.91  2011
3          56120.71  198306.90       NaN  332343.61         332343.61  2011
4           9737.00  182234.59       NaN  326373.19         326373.19  2011
...             ...        ...       ...        ...               ...   ...
148649         0.00       0.00       0.0       0.00              0.00  2014
148650          NaN        NaN       NaN       0.00              0.00  2014
148651          NaN        NaN       NaN       0.00              0.00  2014
148652          NaN        NaN       NaN       0.00              0.00  2014
148653         0.00    -618.13       0.0    -618.13           -618.13  2014

        Notes         Agency  Status
0         NaN  San Francisco     NaN
1         NaN  San Francisco     NaN
2         NaN  San Francisco     NaN
3         NaN  San Francisco     NaN
4         NaN  San Francisco     NaN
...       ...            ...     ...
148649    NaN  San Francisco     NaN
148650    NaN  San Francisco     NaN
148651    NaN  San Francisco     NaN
148652    NaN  San Francisco     NaN
148653    NaN  San Francisco     NaN

[148654 rows x 13 columns]>

In [16]:
df2.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')